name: Continuous Integration

on: push

jobs:
  build_wasm:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - name: Build WASM
        run: dotnet build Spotcheckr.WASM/Spotcheckr.WASM.csproj --configuration Release